import type { Metadata } from "next";
import { ReactNode } from 'react';
import "../globals.css"
import nextI18NextConfig from '../../../next-i18next.config';

export async function generateStaticParams() {
  return nextI18NextConfig.i18n.locales.map(lang => ({ lang }));
}



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function LocaleLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}