import type { Metadata } from 'next';
import { ReactNode } from 'react';
import '../globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function LocaleLayout({ children }: { children: ReactNode }) {
  return <>{children}</>;
}
